javascript:
- javascript/**/*
- javascript/*

javascript-common:
- javascript/modules/common/**/*
- javascript/modules/common/*

javascript-client:
- javascript/modules/client/**/*
- javascript/modules/client/*

javascript-ipfs:
- javascript/modules/ipfs/**/*
- javascript/modules/ipfs/*
